Fix sssd installtion on SLES 15 SP2 and higher
sous-chefs/sssd_ldap pull request #52
Opened 2022-02-02 16:16 UTC by vzabawski

# Description

I've been using this cookbook with SLES 12 and 15 without any issues until SP2 for SLES 15 was released. Starting with this release, sssd-ldap package is optional, so it's not installed by default with sssd and as a result, sssd fails to start. Manual installation of sssd-ldap with subsequent sssd restart fixes this problem, so this PR just adds sssd-ldap installation as an additional step for Suse distros family.

## Check List

- [x] A summary of changes made is included in the CHANGELOG under `## Unreleased`
- [x] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

2022-02-02 17:10 UTC, bmhughes requested changes
Just the version change removal and it looks great

2022-02-02 17:10 UTC, bmhughes commented on metadata.rb
> +version          '5.1.3'
Can you remove the version change please as it gets bumped automatically when the cookbook is released

2022-02-03 08:37 UTC, vzabawski commented
Fixed! :)

2022-02-03 21:43 UTC, ramereth commented
@vzabawski We need to fix our CI pipeline first. If you allow maintainers to edit your branch I can just add that fix to this PR. I'll give it a try first of course.

2022-02-03 23:15 UTC, ramereth commented
@vzabawski looks like I don't have permission:
```
 ! [remote rejected] vzabawski/main -> vzabawski/main (permission denied)
```

2022-02-04 09:28 UTC, vzabawski commented
Hi @ramereth. No problem, I've invited you and @bmhughes as collaborators.

2022-02-04 18:05 UTC, ramereth approved these changes

2022-02-04 18:06 UTC, merged

2022-02-04 18:06 UTC, kitchen-porter commented
Released as: [5.2.0](https://github.com/sous-chefs/sssd_ldap/releases/tag/5.2.0)